"""add rejection_reason to audit_notes

Revision ID: 4e134c9dade0
Revises: 4ec0911d45e2
Create Date: 2026-07-21 23:14:47.399439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e134c9dade0'
down_revision: Union[str, Sequence[str], None] = '4ec0911d45e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_notes', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_notes', 'rejection_reason')
    # ### end Alembic commands ###
