"""add clause_ref and chapter to policies

Revision ID: 4ec0911d45e2
Revises: eb30896dcd72
Create Date: 2026-07-11 13:36:14.073224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec0911d45e2'
down_revision: Union[str, Sequence[str], None] = 'eb30896dcd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('chapter', sa.String(length=255), nullable=True))
    op.add_column('policies', sa.Column('clause_ref', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_policies_clause_ref'), 'policies', ['clause_ref'], unique=False)
    op.create_index(op.f('ix_policies_document_name'), 'policies', ['document_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_document_name'), table_name='policies')
    op.drop_index(op.f('ix_policies_clause_ref'), table_name='policies')
    op.drop_column('policies', 'clause_ref')
    op.drop_column('policies', 'chapter')
    # ### end Alembic commands ###
